### ISSUE TITLE
SwiftUI View에서 method를 관리하기 위한 PDFKitView 수정

### ISSUE THREAD

**Issue by anjiniii** [DeveloperAcademy-POSTECH/2024-NC2-A51-PDFKit#5]
## 📔 Description

SwiftUI View에서 method를 관리하기 위한 PDFKitView 수정을 하고,
Coordinator를 추가해보려고 합니다.

## 🐈 Todo

- [ ] 나우의 코드를 이해하기
- [ ] 분리할 수 있는 부분 파악하기
- [ ] SwiftUI에서 실행할 수 있도록 하기
